### PR TITLE
implemented assignment page view

### PR DESCRIPTION
**Pull request by thennant**
+ made the page for assignment view
+ add uploadfile.png button
- question button yet to be tested
- run code button logic not implemented
- submit button logic not implemented
+ file upload button works but cant tell if it goes to server yet
+ back button works but only goes back to prev webpage, maybe we remove it?
+ assignment description "should" be dynamic but cant test
+ text editor works but doesnt link to submit/run code

### CODE REVIEW

**Comment by weesiau** [comment]
Are we still doing assignments or we going straight from courses to questions?

**Comment by thennant** [comment]
> Are we still doing assignments or we going straight from courses to questions?

I think still doing assignment cos it will contain the assignment description. Then when the user clicks on the question number tab on the side then the assignment description will change to the question? See what the rest say bah

**Comment by weesiau** [comment]
> > Are we still doing assignments or we going straight from courses to questions?
> 
> I think still doing assignment cos it will contain the assignment description. Then when the user clicks on the question number tab on the side then the assignment description will change to the question? See what the rest say bah

@danielk0k @kanna-1 @Saha9616 @Aloynz 
Lets decide this fast since it will affect db schema (need to create that additional layer for assignment). My understanding from prev meeting is that we go straight to questions - course contains multiple questions.

**Comment by danielk0k** [comment]
I think the confusion comes because we have a individual course page `src/app/courses/[courseId]/page.tsx`. Maybe we don't link up the pages first

**Review by danielk0k — COMMENTED** [review]
Will merge and link with backend

**Review by danielk0k — APPROVED** [review]

**Pull request merged**
