### PR TITLE
ITS wrapperclass

### PR DESCRIPTION
**Pull request by kanna-1**
In this PR, we introduce a new route to facilitate interaction with the ITS API. Of the services available on the ITS, we are only interested in three of them: parser, feedback fix, and feedback error.

The parser service is utilized to convert the program into a format compatible with both feedback fix and feedback error services. These latter two services, have similar request format but also differ in their response: feedback fix generates the full feedback, whereas feedback error provides hints to aid students in resolving code issues.

This PR implements the feedback fix API call but I am not able to verify the correctness of the route i.e. I don't think its working. Help will be appreciated 👍

### CODE REVIEW

**Comment by kanna-1** [comment]
Below is a JS file I played with to learn more about the ITS API
```
// This file explores useful ITS API to be used for the front end management system.
// We explore the parser service, feedback fix service, and feedback error service


// Define the reference program

let py_program = `def is_odd(x)
    if x % 2 == 0:
        return False
    else:
        return True`

// Parser Service: Generates a parsed representation of the source_code input in a format specific to the ITS. 
// Any programs to be used as the input of other services must be of this format
/*
Request Format:
- language: c | py
- source_code: string
*/

// // URL for the parser API
const parserApiUrl = 'https://its.comp.nus.edu.sg/cs3213/parser' 

// Body of request 
const requestData = 
{
  "language": "python",
  "source_code": py_program
}

// Generate parsed representation of the c code.
fetch(parserApiUrl, {
    method: 'POST',
    body: JSON.stringify(requestData),
    headers: {
        'Content-Type': 'application/json'
    }
})
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.json();
    })
    .then(data => {
        // console.log(JSON.stringify(data, null, 2)); // We use this format to input to the feedback API
    })
    .catch(error => {
        console.error('Error:', error);
    });

// Feedback fix service:  Generates feedback based on reference, student program, entry function name, inputs & arguments.
// Note: Feedback error works exactly the same way but will only provide hints to the students 
// e.g. based on the line numbers which has issues and their associated error messages (has same request format also)

/*
- language: python | c | py
- reference_solution: string (program)
- student_solution: string (program)
- function: string (the entry function of the program)
- inputs: IO inputs
- args: arguments of the entry function (for e.g. "[2]") (string wrapped in '[]')
*/

// URL for the feedback fix API
const feedbackfixApiUrl = "https://its.comp.nus.edu.sg/cs3213/feedback_fix"

// The work flow is for the reference program and student program, we pass it to the parser service before passing to the feedback service
const ref_program=`def main():
a = 10
b = 0
for i in range(0, a):
    b = b + 1
return b`

const student_program=`def main():
a = 10
b = 0
for i in range(0, a):
    b = b - 1
return b`

const requestDataReferenceProgram = {
    "language": "py",
    "source_code": ref_program
  }

// Make a POST request to the parser API to parse the reference program
async function fetchData() {
    try {
        const parsed_ref_program = await fetch(parserApiUrl, {
            method: 'POST',
            body: JSON.stringify(requestDataReferenceProgram),
            headers: {
                'Content-Type': 'application/json'
            }
        });
        if (!parsed_ref_program.ok) {
            throw new Error('Network response was not ok');
        }
        const data = await parsed_ref_program.json();
        // console.log('Response:', JSON.stringify(data));
        return data;
    } catch (error) {
        console.error('Error:', error);
        throw error;
    }
}

const requestDataStudentSubmission = {
    "language": "py",
    "source_code": student_program
  }

// Make a POST request to the parser API to parse the reference program
async function fetchData2() {
    try {
        const parsed_student_program = await fetch(parserApiUrl, {
            method: 'POST',
            body: JSON.stringify(requestDataStudentSubmission),
            headers: {
                'Content-Type': 'application/json'
            }
        });
        if (!parsed_student_program) {
            throw new Error('Network response was not ok');
        }
        const data = await parsed_student_program.json();
        // console.log('Response:', JSON.stringify(data));
        return data;
    } catch (error) {
        console.error('Error:', error);
        throw error;
    }
}

// Define the request data for feedback generation
Promise.all([fetchData(), fetchData2()])
    .then(([data1, data2]) => {
        // Define the request data for feedback generation using the data from fetchData() and fetchData2()

        // console.log(JSON.stringify(data1, null, 2))
        // console.log(JSON.stringify(data2, null, 2))
        const requestDataFeedback = {
            language: "py",
            reference_solution: JSON.stringify(data1, null, 2), // this format it used (refer to lines 46)
            student_solution: JSON.stringify(data2, null, 2),
            function: "main",
            inputs: "[]",
            args: "",
        };

        // Make a POST request to the feedback fix API using requestDataFeedback
        return fetch(feedbackfixApiUrl, {
            method: 'POST',
            body: JSON.stringify(requestDataFeedback),
            headers: {
                'Content-Type': 'application/json'
            }
        });
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.json();
    })
    .then(data => {
        console.log('Response:', data);
    })
    .catch(error => {
        console.error('Error:', error);
    });

// If we replace the url from https://its.comp.nus.edu.sg/cs3213/feedback_fix to https://its.comp.nus.edu.sg/cs3213/feedback_error,
// The response will detailed ITS hints, but without the full repair, so that we don't show the student how exactly to fix their program. 
// Currently it will contain the line numbers which has issues, and their associated error message.





```

**Comment by danielk0k** [comment]
Thanks for the good work!
1. To clarify `/cs3213/feedback_error` returns where you've gone wrong and `/cs3213/feedback_fix` returns where you've gone wrong + how to fix it
2. The ITS API seems to be working for me. What errors are you getting?

**Comment by danielk0k** [comment]
I guess we'll probably have to link it up with a frontend to see if it works. Maybe you can have a look at #13 and use the sample test page I made to test `api/get-data/get-feedback`.

We can sync up on this 👍🏻

**Review by danielk0k — APPROVED** [review]
Will merge and link with frontend

**Pull request merged**
